
pointers_and_data_structures: pointers_and_data_structures.c
	gcc pointers_and_data_structures.c -o pointers_and_data_structures

run:
	./pointers_and_data_structures

clean:
	rm pointers_and_data_structures

